### ISSUE TITLE
Roadmap to Specification

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/MicroWaveDeviceInventory#1]
### Collaboration

- [x] Read [Introduction to Git and GitHub](https://github.com/openBackhaul/ApplicationPattern/blob/tsi/doc/PreparingSpecifying/Introduction2Git/Introduction2Git.md)
- [x] Read [Workflow for Contributing](https://github.com/openBackhaul/ApplicationPattern/blob/tsi/doc/PreparingSpecifying/WorkflowForContributing/WorkflowForContributing.md)
- [x] Read [GitFlow Workflow](https://github.com/openBackhaul/ApplicationPattern/blob/tsi/doc/PreparingSpecifying/GitFlowWorkflow/GitFlowWorkflow.md)
- #002
- #003
- #004
- #005
- [x] Make yourself familiar with the [Basic Syntax of Markdown](https://www.markdownguide.org/basic-syntax/)
- [x] Read [Formulating Issues](https://github.com/openBackhaul/ApplicationPattern/blob/tsi/doc/PreparingSpecifying/FormulatingIssues/FormulatingIssues.md)
- [x] Read [Formulating Commit and Merge Request Messages](https://github.com/openBackhaul/ApplicationPattern/blob/tsi/doc/PreparingSpecifying/FormulatingCommitMessages/FormulatingCommitMessages.md)
- [x] Read [Management of Conflicts](https://github.com/openBackhaul/ApplicationPattern/blob/tsi/doc/PreparingSpecifying/ConflictManagement/ConflictManagement.md)
- [x] Read [Avoiding Conflicts](https://github.com/openBackhaul/ApplicationPattern/blob/tsi/doc/PreparingSpecifying/AvoidingConflicts/AvoidingConflicts.md)
- #006

#### ServiceList

- [x] Read [Structure of Services](https://github.com/openBackhaul/ApplicationPattern/tree/develop/doc/SpecifyingApplications/StructureOfServices/StructureOfServices.md)
- [x] Read [Structure of ServiceNames](https://github.com/openBackhaul/ApplicationPattern/tree/develop/doc/SpecifyingApplications/StructureOfServiceNames/StructureOfServiceNames.md)
- [x] Read [Structure of Release Numbers](https://github.com/openBackhaul/ApplicationPattern/tree/develop/doc/SpecifyingApplications/StructureOfReleaseNumbers/StructureOfReleaseNumbers.md)
- [x] Read [Structure of UUIDs](https://github.com/openBackhaul/ApplicationPattern/tree/develop/doc/SpecifyingApplications/StructureOfUuids/StructureOfUuids.md) in general and for details about Servers and Clients
- [x] Read [Concept of ServiceList](https://github.com/openBackhaul/ApplicationPattern/tree/develop/doc/SpecifyingApplications/ConceptOfServiceList/ConceptOfServiceList.md)
- [x] #017

#### ProfileList

- [x] Read [Concept of Profiles](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/SpecifyingApplications/ConceptOfProfiles/ConceptOfProfiles.md)
- [x] [Structure of UUIDs](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/SpecifyingApplications/StructureOfUuids/StructureOfUuids.md) in general and for details about Profiles
- [x] Read [Concepts of ProfileList and ProfileInstanceList](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/SpecifyingApplications/ConceptOfProfileList/ConceptOfProfileList.md)
- [x] #018
- [x] #019

#### ForwardingList

- [x] Read [Concepts of Internal Forwarding](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ElementsApplicationPattern/Functions/ConceptsOfInternalForwarding/ConceptsOfInternalForwarding.md)
- [x] Read [Structure of Internal Forwardings](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ElementsApplicationPattern/Functions/StructureOfInternalForwarding/StructureOfInternalForwarding.md)
- [x] Read [Types of Internal Forwardings](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ElementsApplicationPattern/Functions/TypesOfInternalForwardings/TypesOfInternalForwardings.md)
- [x] Read [Substructure of Management of Internal Forwarding](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ElementsApplicationPattern/Functions/SubstructureOfManagementOfInternalForwardings/SubstructureOfManagementOfInternalForwardings.md)
- [x] Read [Structure of Internal Forwarding Names](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ElementsApplicationPattern/Names/StructureOfInternalForwardingNames/StructureOfInternalForwardingNames.md)
- [x] Read [Concepts of the _ForwardingList_](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/SpecifyingApplications/ConceptsOfForwardingList/ConceptsOfForwardingList.md)
- [x] Read [Structure of the _ForwardingList_](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/SpecifyingApplications/StructureOfForwardingList/StructureOfForwardingList.md)
- [x] Read [Structure of a Description of a _Forwarding_](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/SpecifyingApplications/StructureOfForwardingDescription/StructureOfForwardingDescription.md)
- [x] #080

#### CONFIGfile

- [x] Read [Concept of the CONFIGfile](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ElementsApplicationPattern/Functions/ConceptOfConfigFile/ConceptOfConfigFile.md)
- [x] Read [Concept of the DATAfile](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ElementsApplicationPattern/Functions/ConceptOfDataFile/ConceptOfDataFile.md)
- [x] Read [Structure of the CONFIGfile](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ElementsApplicationPattern/Functions/StructureOfConfigFile/StructureOfConfigFile.md)
- [x] Read [ONF Core Model Overview](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ElementsApplicationPattern/InformationModel/Overview/Overview.md)
- [x] Read [ControlConstruct](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ElementsApplicationPattern/InformationModel/ControlConstruct/ControlConstruct.md)
- [x] Read [ProfileCollection and Profile](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ElementsApplicationPattern/InformationModel/Profile/Profile.md)
- [x] Read [LogicalTerminationPoint and LayerProtocol](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ElementsApplicationPattern/InformationModel/LogicalTerminationPoint/LogicalTerminationPoint.md)
- [x] Read [ForwardingDomain, ForwardingConstruct and ForwardingConstructPort](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ElementsApplicationPattern/InformationModel/ForwardingConstruct/ForwardingConstruct.md)
- [x] #086
  - [x] Read [Creating the CONFIGfile]

Continued in #123

**Comment by kmohr-soprasteria** [comment]
Note on ProfileList: no additional profiles needed for now -> no modification.  
ProfileListInstances could be extended with additional action profiles.
