### ISSUE TITLE
Roadmap to Specification

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/MicroWaveDeviceInventory#123]
#### OAS

- [x] Read [Concept of Microservice](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ElementsApplicationPattern/Principles/Microservice/Microservice.md)
- (['Microservices' at Wikipedia site](https://de.wikipedia.org/wiki/Microservices) could also be read for a bit more complete picture)
- [ ] Read [Introduction to HTTP Requests](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ElementsApplicationPattern/Principles/Http/Http.md)
- [ ] Read about the [API-First Approach](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ElementsApplicationPattern/Principles/ApiFirst/ApiFirst.md)
- [ ] Read about the [OpenAPI Specification](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ElementsApplicationPattern/Principles/OpenApiSpecification/OpenApiSpecification.md) definitions
- [ ] Read the [OpenAPI Guide from Basic Structure to Using $ref](https://swagger.io/docs/specification/basic-structure/)
- (In case of any doubts during applying OpenAPI Specification, looking into its [definition](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#oasDocument) might help, but it is not recommended to read the entire document.)
- [ ] Open an existing OAS (e.g. [RegistryOffice](https://github.com/openBackhaul/RegistryOffice/blob/develop/spec/RegistryOffice.yaml)) and study it line by line while reading [Structure of the OAS](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/SpecifyingApplications/StructureOfOas/StructureOfOas.md)
- [ ] #124
